on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '12 9 * * 4'

jobs:
  SCS:
    runs-on: windows-latest
    steps:     
      - uses: actions/checkout@v2
      - uses: nuget/setup-nuget@v1.0.5
      - uses: microsoft/setup-msbuild@v1.0.2

      - name: Set up projects
        uses: security-code-scan/security-code-scan-add-action@main

      - name: Build
        run: |
          nuget restore
          msbuild
          type ./FullDotNetWebApp/analysis.sarif	
          type ./FullDotNetWebApp2/analysis.sarif
        
      - name: Convert sarif for uploading to GitHub
        uses: jarlob/security-code-scan-results-action@main
      - name: converted	
        run: |	
          type ../results/0.sarif	
          type ../results/1.sarif
        
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v1
